// frontend/src/pages/Disclaimer.jsx
// Tripzio Legal — AI Content Disclaimer + Affiliate Disclosure

import { useNavigate } from 'react-router-dom'
import Navbar from '../components/Navbar'

export default function Disclaimer() {
  const navigate = useNavigate()

  return (
    <div style={{ minHeight: '100vh', background: '#f8fafc', fontFamily: 'Inter, sans-serif' }}>
      <Navbar />
      <div style={{ maxWidth: '800px', margin: '0 auto', padding: '48px 24px 80px' }}>

        <div style={{ marginBottom: '40px' }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', background: '#f0fdfa', border: '1px solid #99f6e4', borderRadius: '20px', padding: '5px 14px', marginBottom: '16px' }}>
            <span style={{ fontSize: '11px', color: '#0d9488', fontWeight: '700', letterSpacing: '1px', textTransform: 'uppercase' }}>Legal</span>
          </div>
          <h1 style={{ fontSize: '36px', fontWeight: '900', color: '#0f172a', margin: '0 0 8px', letterSpacing: '-0.5px' }}>Disclaimer</h1>
          <p style={{ fontSize: '14px', color: '#64748b', margin: 0 }}>AI Content Disclaimer & Affiliate Disclosure</p>
        </div>

        {/* AI Disclaimer — most important */}
        <div style={{ background: '#fef2f2', border: '1.5px solid #fecaca', borderRadius: '16px', padding: '24px', marginBottom: '28px' }}>
          <h2 style={{ fontSize: '16px', fontWeight: '800', color: '#991b1b', margin: '0 0 12px' }}>⚠️ AI-Generated Content Disclaimer</h2>
          <p style={{ fontSize: '14px', color: '#7f1d1d', lineHeight: 1.8, margin: 0 }}>
            All travel itineraries, hotel suggestions, cost estimates, attraction recommendations, and travel tips generated by Tripzio are created by artificial intelligence. These are <strong>suggestions only</strong> and may not accurately reflect current real-world conditions.
          </p>
          <ul style={{ fontSize: '14px', color: '#7f1d1d', lineHeight: 2, margin: '12px 0 0', paddingLeft: '20px' }}>
            <li>Hotel names and details may have changed since AI training</li>
            <li>Prices are estimates only — actual prices will vary</li>
            <li>Some suggested hotels or attractions may no longer exist</li>
            <li>Travel distances and durations are approximate</li>
            <li>Always independently verify all details before travelling</li>
          </ul>
          <p style={{ fontSize: '13px', color: '#991b1b', fontWeight: '700', margin: '12px 0 0' }}>
            Tripzio is not liable for any loss or inconvenience arising from reliance on AI-generated content.
          </p>
        </div>

        {/* Affiliate Disclosure */}
        <div style={{ background: '#fffbeb', border: '1.5px solid #fcd34d', borderRadius: '16px', padding: '24px', marginBottom: '28px' }}>
          <h2 style={{ fontSize: '16px', fontWeight: '800', color: '#92400e', margin: '0 0 12px' }}>💰 Affiliate Disclosure</h2>
          <p style={{ fontSize: '14px', color: '#78350f', lineHeight: 1.8, margin: '0 0 12px' }}>
            Tripzio participates in affiliate marketing programs. When you click hotel booking links on our platform and make a purchase, we may earn a commission from our affiliate partners including:
          </p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(180px,1fr))', gap: '10px', marginBottom: '12px' }}>
            {['Booking.com', 'Agoda', 'TripAdvisor', 'Zostel'].map(partner => (
              <div key={partner} style={{ background: 'white', border: '1px solid #fcd34d', borderRadius: '8px', padding: '10px 14px', fontSize: '13px', fontWeight: '700', color: '#92400e', textAlign: 'center' }}>
                {partner}
              </div>
            ))}
          </div>
          <p style={{ fontSize: '14px', color: '#78350f', lineHeight: 1.8, margin: 0 }}>
            <strong>This comes at no extra cost to you.</strong> Affiliate commissions help us keep Tripzio running and improving. Our hotel suggestions are based on relevance to your trip — not on commission rates.
          </p>
        </div>

        {/* Hotel Suggestions */}
        <div style={{ background: '#eff6ff', border: '1.5px solid #bfdbfe', borderRadius: '16px', padding: '24px', marginBottom: '28px' }}>
          <h2 style={{ fontSize: '16px', fontWeight: '800', color: '#1e40af', margin: '0 0 12px' }}>🏨 Hotel Suggestion Disclaimer</h2>
          <p style={{ fontSize: '14px', color: '#1e3a8a', lineHeight: 1.8, margin: 0 }}>
            Hotel suggestions shown in Tripzio itineraries are for reference only. Tripzio:
          </p>
          <ul style={{ fontSize: '14px', color: '#1e3a8a', lineHeight: 2, margin: '8px 0 0', paddingLeft: '20px' }}>
            <li>Does not guarantee hotel availability</li>
            <li>Does not guarantee displayed prices are current</li>
            <li>Is not responsible for hotel quality or service</li>
            <li>Does not have partnerships with most suggested hotels</li>
            <li>Recommends verifying all hotels on TripAdvisor, Booking.com, or Google before booking</li>
          </ul>
        </div>

        {/* Festival Data */}
        <div style={{ background: '#f0fdf4', border: '1.5px solid #86efac', borderRadius: '16px', padding: '24px', marginBottom: '28px' }}>
          <h2 style={{ fontSize: '16px', fontWeight: '800', color: '#166534', margin: '0 0 12px' }}>🎪 Festival Calendar Disclaimer</h2>
          <p style={{ fontSize: '14px', color: '#14532d', lineHeight: 1.8, margin: 0 }}>
            Festival dates shown by Tripzio are based on our database which is updated annually. However:
          </p>
          <ul style={{ fontSize: '14px', color: '#14532d', lineHeight: 2, margin: '8px 0 0', paddingLeft: '20px' }}>
            <li>Hindu and Islamic festival dates vary by lunar calendar and may differ slightly</li>
            <li>Event cancellations due to unforeseen circumstances are not reflected</li>
            <li>Hotel price estimates during festivals are approximate</li>
            <li>Always confirm festival dates with official sources before planning</li>
          </ul>
        </div>

        {/* Pricing */}
        <div style={{ background: '#f5f3ff', border: '1.5px solid #ddd6fe', borderRadius: '16px', padding: '24px', marginBottom: '28px' }}>
          <h2 style={{ fontSize: '16px', fontWeight: '800', color: '#5b21b6', margin: '0 0 12px' }}>💸 Price Estimate Disclaimer</h2>
          <p style={{ fontSize: '14px', color: '#4c1d95', lineHeight: 1.8, margin: 0 }}>
            Budget estimates in Tripzio itineraries are approximate and based on average prices. Actual costs may vary based on season, availability, personal preferences, and market conditions. Tripzio is not responsible for any financial decisions made based on these estimates.
          </p>
        </div>

        {/* Contact */}
        <div style={{ background: 'white', border: '1px solid #e2e8f0', borderRadius: '16px', padding: '24px', marginBottom: '28px' }}>
          <h2 style={{ fontSize: '16px', fontWeight: '800', color: '#0f172a', margin: '0 0 12px' }}>📧 Questions?</h2>
          <p style={{ fontSize: '14px', color: '#475569', lineHeight: 1.8, margin: 0 }}>
            For questions about this disclaimer or our practices:<br />
            <strong>Email:</strong> legal@tripzio.io<br />
            <strong>Website:</strong> tripzio.io
          </p>
        </div>

        <div style={{ textAlign: 'center', marginTop: '40px', paddingTop: '24px', borderTop: '1px solid #e2e8f0' }}>
          <button onClick={() => navigate(-1)} style={{ padding: '10px 24px', background: '#0d9488', color: 'white', border: 'none', borderRadius: '10px', fontSize: '13px', fontWeight: '700', cursor: 'pointer' }}>
            ← Back
          </button>
        </div>
      </div>
    </div>
  )
}
