// frontend/src/pages/TermsOfService.jsx
// Tripzio Legal — Terms of Service
// Compliant with: Indian Contract Act 1872, IT Act 2000, Consumer Protection Act 2019

import { useNavigate } from 'react-router-dom'
import Navbar from '../components/Navbar'

export default function TermsOfService() {
  const navigate = useNavigate()
  const lastUpdated = 'May 2026'

  return (
    <div style={{ minHeight: '100vh', background: '#f8fafc', fontFamily: 'Inter, sans-serif' }}>
      <Navbar />
      <div style={{ maxWidth: '800px', margin: '0 auto', padding: '48px 24px 80px' }}>

        <div style={{ marginBottom: '40px' }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', background: '#f0fdfa', border: '1px solid #99f6e4', borderRadius: '20px', padding: '5px 14px', marginBottom: '16px' }}>
            <span style={{ fontSize: '11px', color: '#0d9488', fontWeight: '700', letterSpacing: '1px', textTransform: 'uppercase' }}>Legal</span>
          </div>
          <h1 style={{ fontSize: '36px', fontWeight: '900', color: '#0f172a', margin: '0 0 8px', letterSpacing: '-0.5px' }}>Terms of Service</h1>
          <p style={{ fontSize: '14px', color: '#64748b', margin: 0 }}>Last updated: {lastUpdated}</p>
        </div>

        <div style={{ background: '#fffbeb', border: '1px solid #fcd34d', borderRadius: '12px', padding: '16px 20px', marginBottom: '32px' }}>
          <p style={{ fontSize: '13px', color: '#92400e', margin: 0, lineHeight: 1.6 }}>
            <strong>Summary:</strong> Tripzio is an AI trip planning tool. We plan trips — we don't book them. AI-generated itineraries are suggestions only. Always verify hotel and travel details before booking. By using Tripzio, you agree to these terms.
          </p>
        </div>

        {[
          {
            title: '1. Acceptance of Terms',
            content: `By accessing or using Tripzio ("Service") at tripzio.io, you agree to be bound by these Terms of Service. If you do not agree, please do not use our Service.

These Terms constitute a legally binding agreement under the Indian Contract Act 1872 between you and Tripzio.`
          },
          {
            title: '2. What Tripzio Is',
            content: `Tripzio is an AI-powered trip planning platform. We help users and travel agents plan trips within India.

Tripzio IS:
• An AI trip itinerary generator
• A travel planning assistant
• An agent productivity tool
• A trip sharing platform

Tripzio is NOT:
• A travel booking platform
• A hotel reservation system  
• A travel agency
• A guarantor of any travel service quality`
          },
          {
            title: '3. AI-Generated Content Disclaimer',
            content: `IMPORTANT: All itineraries, hotel suggestions, cost estimates, and travel recommendations generated by Tripzio are created by artificial intelligence and are provided AS SUGGESTIONS ONLY.

Tripzio expressly disclaims responsibility for:
• Accuracy of hotel names, addresses, or availability
• Accuracy of price estimates
• Accuracy of travel distances or durations
• Accuracy of tourist attraction information
• Changes in hotel operations, closures, or quality

Always independently verify:
✓ Hotel availability and current prices
✓ Transport schedules and fares  
✓ Tourist attraction opening hours
✓ Visa and permit requirements
✓ Weather conditions

Tripzio is not liable for any loss, inconvenience, or expense arising from reliance on AI-generated content.`
          },
          {
            title: '4. Hotel and Travel Suggestions',
            content: `When Tripzio suggests hotels or travel services:

• Suggestions are based on AI training data and may not reflect current status
• We may display links to third-party booking platforms (Booking.com, Agoda, TripAdvisor)
• Clicking these links takes you to third-party websites governed by their own terms
• Tripzio may earn an affiliate commission when you book through partner links — at no extra cost to you
• We do not guarantee prices, availability, or quality of third-party services
• All bookings are contracts between you and the hotel/service provider directly

Affiliate Disclosure: Tripzio participates in affiliate programs. We earn commissions on qualifying bookings. This does not influence our recommendations.`
          },
          {
            title: '5. User Accounts',
            content: `5.1 You must provide accurate information when registering.
5.2 You are responsible for maintaining the security of your password.
5.3 You must be 18 years or older to use Tripzio.
5.4 One person may not maintain multiple free accounts to circumvent plan limits.
5.5 We reserve the right to suspend accounts that violate these terms.`
          },
          {
            title: '6. Agent Accounts — Additional Terms',
            content: `Travel agents using Tripzio agree to:

6.1 Only store client data with clients' knowledge and consent
6.2 Not upload false or misleading client information  
6.3 Use Tripzio-generated PDFs only for legitimate travel planning purposes
6.4 Not misrepresent Tripzio's AI-generated content as independently researched plans
6.5 Inform clients that itineraries are AI-generated and require independent verification
6.6 Comply with all applicable travel agency regulations in their jurisdiction

Tripzio is not responsible for any disputes between agents and their clients.`
          },
          {
            title: '7. Subscription and Payments',
            content: `7.1 Free tier: Limited to 3 AI-generated plans per month
7.2 Paid subscriptions are billed monthly
7.3 Prices are in Indian Rupees (INR) inclusive of applicable taxes
7.4 Subscriptions auto-renew unless cancelled before the billing date
7.5 Refunds: We offer a 7-day refund for first-time subscribers if unsatisfied

Current pricing:
• User Free: ₹0 (3 plans/month)
• User Pro: ₹99/month (unlimited plans)  
• Agent Starter: ₹499/month (25 clients)
• Agent Pro: ₹999/month (unlimited clients + white label)

Prices may change with 30 days notice.`
          },
          {
            title: '8. Intellectual Property',
            content: `8.1 Tripzio platform, design, and code are owned by Tripzio.
8.2 AI-generated itineraries generated using your inputs belong to you.
8.3 You grant Tripzio a license to use anonymised trip data to improve our AI.
8.4 You may not copy, reverse engineer, or resell Tripzio's platform or technology.
8.5 White-label PDFs generated by agents may be shared with their clients.`
          },
          {
            title: '9. Prohibited Uses',
            content: `You may not use Tripzio to:
• Generate content for illegal activities
• Spam or harass other users
• Attempt to access others' accounts
• Scrape or systematically extract data
• Use automated bots to generate plans
• Misrepresent AI-generated plans as human-researched content to deceive clients
• Violate any applicable Indian or international law`
          },
          {
            title: '10. Limitation of Liability',
            content: `To the maximum extent permitted by Indian law:

Tripzio's total liability for any claim arising from use of our Service is limited to the amount you paid us in the 3 months preceding the claim.

We are not liable for:
• Indirect, incidental, or consequential damages
• Loss of profits or business opportunity
• Travel disruptions, cancellations, or losses
• Third-party service failures
• Force majeure events

This limitation applies even if we have been advised of the possibility of such damages.`
          },
          {
            title: '11. India-Only Service',
            content: `Tripzio currently provides trip planning for Indian destinations only. International destination planning is not supported. We expressly disclaim responsibility for any attempted use of Tripzio for international travel planning.`
          },
          {
            title: '12. Governing Law',
            content: `These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in Kolkata, West Bengal, India.

For consumer disputes, you may also approach the relevant Consumer Disputes Redressal Forum under the Consumer Protection Act 2019.`
          },
          {
            title: '13. Changes to Terms',
            content: `We may update these Terms with 30 days notice for material changes. Continued use after notice constitutes acceptance. For non-material changes, updated terms take effect immediately upon posting.`
          },
          {
            title: '14. Contact',
            content: `For terms-related queries:
Email: legal@tripzio.io
Website: tripzio.io/terms`
          },
        ].map((section, i) => (
          <div key={i} style={{ marginBottom: '32px' }}>
            <h2 style={{ fontSize: '18px', fontWeight: '800', color: '#0f172a', margin: '0 0 12px', paddingBottom: '8px', borderBottom: '2px solid #f1f5f9' }}>{section.title}</h2>
            <p style={{ fontSize: '14px', color: '#475569', lineHeight: 1.8, margin: 0, whiteSpace: 'pre-line' }}>{section.content}</p>
          </div>
        ))}

        <div style={{ textAlign: 'center', marginTop: '48px', paddingTop: '24px', borderTop: '1px solid #e2e8f0' }}>
          <button onClick={() => navigate(-1)} style={{ padding: '10px 24px', background: '#0d9488', color: 'white', border: 'none', borderRadius: '10px', fontSize: '13px', fontWeight: '700', cursor: 'pointer' }}>
            ← Back
          </button>
        </div>
      </div>
    </div>
  )
}
