import { useNavigate } from 'react-router-dom'
import Navbar from '../components/Navbar'

export default function TermsOfService() {
  const navigate = useNavigate()

  const Section = ({ title, children }) => (
    <div style={{ marginBottom: '32px' }}>
      <h2 style={{ fontSize: '18px', fontWeight: '800', color: '#0f172a', marginBottom: '12px', fontFamily: "'Plus Jakarta Sans', sans-serif" }}>{title}</h2>
      <div style={{ fontSize: '14px', color: '#475569', lineHeight: 1.8 }}>{children}</div>
    </div>
  )

  return (
    <div style={{ minHeight: '100vh', background: '#f8fafc', fontFamily: 'Inter, sans-serif' }}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@700;800;900&display=swap');`}</style>
      <Navbar />
      <div style={{ maxWidth: '760px', margin: '0 auto', padding: '48px 24px' }}>
        <button onClick={() => navigate(-1)}
          style={{ background: 'none', border: 'none', color: '#64748b', fontSize: '14px', fontWeight: '600', cursor: 'pointer', marginBottom: '24px', padding: 0 }}>
          ← Back
        </button>
        <div style={{ background: 'white', borderRadius: '24px', padding: '48px', boxShadow: '0 2px 16px rgba(0,0,0,0.06)' }}>
          <div style={{ marginBottom: '36px' }}>
            <h1 style={{ fontSize: '32px', fontWeight: '900', color: '#0f172a', margin: '0 0 8px', fontFamily: "'Plus Jakarta Sans', sans-serif" }}>Terms of Service</h1>
            <p style={{ fontSize: '13px', color: '#94a3b8', margin: 0 }}>Last updated: April 2026</p>
          </div>

          <Section title="1. Acceptance">
            <p>By using Tripzio ("the Service"), you agree to these Terms. If you disagree, please do not use the Service. These terms apply to all users including visitors, registered users, and travel agents.</p>
          </Section>

          <Section title="2. The Service">
            <p style={{ marginBottom: '12px' }}>Tripzio is an AI-powered travel planning platform. We help you plan trips to Indian destinations using artificial intelligence.</p>
            <p style={{ marginBottom: '8px' }}>• <strong>AI-generated content:</strong> Itineraries are generated by AI and are suggestions only. Always verify critical information like train schedules, hotel availability, and permit requirements independently.</p>
            <p>• <strong>Not a booking platform:</strong> Tripzio helps you plan. Bookings happen through third-party providers (IRCTC, Booking.com, etc.) and are subject to their terms.</p>
          </Section>

          <Section title="3. User Accounts">
            <p style={{ marginBottom: '8px' }}>• You must provide accurate information when registering</p>
            <p style={{ marginBottom: '8px' }}>• You are responsible for maintaining your account security</p>
            <p style={{ marginBottom: '8px' }}>• You must be 18 or older to use Tripzio</p>
            <p>• One account per person — creating multiple accounts is not permitted</p>
          </Section>

          <Section title="4. Acceptable Use">
            <p style={{ marginBottom: '10px' }}>You agree NOT to:</p>
            <p style={{ marginBottom: '8px' }}>• Use Tripzio for any illegal purpose</p>
            <p style={{ marginBottom: '8px' }}>• Attempt to hack, scrape, or abuse the platform</p>
            <p style={{ marginBottom: '8px' }}>• Resell or commercially exploit AI-generated content without permission</p>
            <p>• Impersonate other users or provide false information</p>
          </Section>

          <Section title="5. AI Content Disclaimer">
            <p style={{ marginBottom: '12px' }}>Tripzio uses AI to generate travel plans. While we strive for accuracy:</p>
            <p style={{ marginBottom: '8px' }}>• Hotel prices, train schedules, and entry fees change frequently. Always verify before booking.</p>
            <p style={{ marginBottom: '8px' }}>• Permit requirements and road conditions should be verified with official sources.</p>
            <p>• Tripzio is not liable for any losses arising from decisions made based on AI-generated content.</p>
          </Section>

          <Section title="6. Subscriptions and Payments">
            <p style={{ marginBottom: '8px' }}>• Free tier includes limited itinerary generations per month</p>
            <p style={{ marginBottom: '8px' }}>• Paid subscriptions are billed monthly via Razorpay</p>
            <p style={{ marginBottom: '8px' }}>• Subscriptions auto-renew unless cancelled before the renewal date</p>
            <p>• Refunds are handled on a case-by-case basis — contact hello@tripzio.io</p>
          </Section>

          <Section title="7. Intellectual Property">
            <p style={{ marginBottom: '8px' }}>• Tripzio and its branding are owned by Avik Chakraborty</p>
            <p style={{ marginBottom: '8px' }}>• AI-generated itineraries are provided for your personal use</p>
            <p>• You may share itineraries for personal, non-commercial purposes</p>
          </Section>

          <Section title="8. Limitation of Liability">
            <p>Tripzio is provided "as is". We are not liable for any indirect, incidental, or consequential damages arising from use of the Service. Our maximum liability is limited to the amount you paid us in the last 3 months.</p>
          </Section>

          <Section title="9. Changes to Terms">
            <p>We may update these terms occasionally. We'll notify you via email for significant changes. Continued use after changes means you accept the new terms.</p>
          </Section>

          <Section title="10. Contact">
            <p>Email: hello@tripzio.io · Website: tripzio.io · Kolkata, India</p>
          </Section>

          <div style={{ paddingTop: '24px', borderTop: '1px solid #f1f5f9' }}>
            <p style={{ fontSize: '13px', color: '#94a3b8', textAlign: 'center' }}>
              Tripzio · Kolkata, India · hello@tripzio.io · tripzio.io
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
