/**
 * frontend/src/utils/generatePDF.js
 * Tripzio — Beautiful PDF Generator (User + Agent)
 *
 * Install dependency first:
 *   npm install jspdf
 *
 * Usage in ItineraryResult.jsx:
 *   import { generateTripPDF } from '../utils/generatePDF'
 *   generateTripPDF({ data, user, isAgent, clientName })
 */

import { jsPDF } from 'jspdf'

// ── Brand colors ──────────────────────────────────────────────
const C = {
  teal:       [13, 148, 136],    // #0d9488
  tealLight:  [240, 253, 250],   // #f0fdfa
  tealDark:   [15, 118, 110],    // #0f766e
  navy:       [15, 23, 42],      // #0f172a
  slate:      [100, 116, 139],   // #64748b
  slateLight: [241, 245, 249],   // #f1f5f9
  white:      [255, 255, 255],
  black:      [0, 0, 0],
  gold:       [245, 158, 11],    // #f59e0b
  green:      [22, 163, 74],     // #16a34a
  greenLight: [240, 253, 244],
  red:        [239, 68, 68],
  border:     [226, 232, 240],   // #e2e8f0
}

const TIER_COLOR = {
  bronze:   [146, 64,  14],
  silver:   [51,  65,  85],
  gold:     [146, 64,  14],
  diamond:  [29,  78,  216],
  platinum: [107, 33,  168],
}

const TIER_EMOJI_LABEL = {
  bronze:   '🥉 BRONZE',
  silver:   '🥈 SILVER',
  gold:     '🥇 GOLD',
  diamond:  '💎 DIAMOND',
  platinum: '✨ PLATINUM',
}

// ── Helpers ───────────────────────────────────────────────────

const rgb = (arr) => ({ r: arr[0], g: arr[1], b: arr[2] })

function setFill(doc, arr)   { doc.setFillColor(arr[0], arr[1], arr[2]) }
function setDraw(doc, arr)   { doc.setDrawColor(arr[0], arr[1], arr[2]) }
function setTextC(doc, arr)  { doc.setTextColor(arr[0], arr[1], arr[2]) }

function rect(doc, x, y, w, h, fill, r = 0) {
  setFill(doc, fill)
  if (r > 0) doc.roundedRect(x, y, w, h, r, r, 'F')
  else doc.rect(x, y, w, h, 'F')
}

function line(doc, x1, y1, x2, y2, color = C.border, lw = 0.3) {
  doc.setLineWidth(lw)
  setDraw(doc, color)
  doc.line(x1, y1, x2, y2)
}

function text(doc, str, x, y, opts = {}) {
  const { size = 10, bold = false, color = C.navy, align = 'left', maxWidth } = opts
  doc.setFontSize(size)
  doc.setFont('helvetica', bold ? 'bold' : 'normal')
  setTextC(doc, color)
  if (maxWidth) {
    const lines = doc.splitTextToSize(String(str || ''), maxWidth)
    doc.text(lines, x, y, { align })
    return lines.length
  }
  doc.text(String(str || ''), x, y, { align })
  return 1
}

function wrap(doc, str, x, y, maxWidth, opts = {}) {
  const { size = 9, color = C.slate, lineH = 5 } = opts
  doc.setFontSize(size)
  doc.setFont('helvetica', 'normal')
  setTextC(doc, color)
  const lines = doc.splitTextToSize(String(str || ''), maxWidth)
  doc.text(lines, x, y)
  return lines.length * lineH
}

// Check if new page needed, add one if so
function checkPage(doc, y, needed = 30) {
  if (y + needed > 270) {
    doc.addPage()
    return 20
  }
  return y
}

// ── Section header ─────────────────────────────────────────────
function sectionHeader(doc, y, label, icon = '') {
  rect(doc, 14, y, 182, 8, C.tealLight, 3)
  text(doc, `${icon}  ${label}`, 19, y + 5.5, { size: 10, bold: true, color: C.tealDark })
  return y + 12
}

// ── Pill badge ─────────────────────────────────────────────────
function pill(doc, x, y, label, bgColor, textColor) {
  const w = doc.getTextWidth(label) + 8
  rect(doc, x, y - 4, w, 6, bgColor, 3)
  text(doc, label, x + 4, y, { size: 7.5, bold: true, color: textColor })
  return w
}

// ── Page header (repeated on each page after first) ──────────
function miniHeader(doc, destination) {
  rect(doc, 0, 0, 210, 10, C.navy)
  text(doc, 'TRIPZIO', 14, 6.5, { size: 7, bold: true, color: C.teal })
  text(doc, `| ${destination}`, 35, 6.5, { size: 7, color: C.slate })
  text(doc, 'tripzio.io', 196, 6.5, { size: 7, color: C.slate, align: 'right' })
}

// ── Footer ────────────────────────────────────────────────────
function footer(doc, pageNum, totalPages, isAgent, agentName) {
  const y = 285
  line(doc, 14, y, 196, y, C.border)
  const left = isAgent
    ? `Prepared by ${agentName} · Powered by Tripzio AI`
    : 'Generated by Tripzio AI · tripzio.io'
  text(doc, left, 14, y + 5, { size: 7.5, color: C.slate })
  text(doc, `Page ${pageNum} of ${totalPages}`, 196, y + 5, { size: 7.5, color: C.slate, align: 'right' })
}

// ─────────────────────────────────────────────────────────────
// MAIN EXPORT
// ─────────────────────────────────────────────────────────────

export function generateTripPDF({ data, user, isAgent = false, clientName = null }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const PW = 210, ML = 14, MR = 196, CW = MR - ML  // page width, margins, content width

  const agentName  = user?.business_name || user?.full_name || 'Travel Agent'
  const userName   = user?.full_name || 'Traveler'
  const tierColor  = TIER_COLOR[data.plan_tier] || TIER_COLOR.silver
  const tierLabel  = TIER_EMOJI_LABEL[data.plan_tier] || 'SILVER'

  // ── PAGE 1 — HERO ────────────────────────────────────────────
  // Dark hero header
  rect(doc, 0, 0, PW, 72, C.navy)

  // Teal accent bar
  rect(doc, 0, 0, PW, 2, C.teal)

  // Tripzio wordmark
  text(doc, 'TRIPZIO', ML, 12, { size: 11, bold: true, color: C.teal })
  text(doc, 'AI Travel Planner', ML + 28, 12, { size: 8, color: C.slate })
  text(doc, 'tripzio.io', MR, 12, { size: 8, color: C.slate, align: 'right' })

  // Tier pill
  rect(doc, ML, 17, 30, 7, tierColor, 3)
  text(doc, tierLabel, ML + 15, 22, { size: 7.5, bold: true, color: C.white, align: 'center' })

  // Destination
  text(doc, data.destination || 'Your Trip', ML, 38, { size: 26, bold: true, color: C.white })

  // Trip meta pills
  const metaItems = [
    `📅 ${data.days} Days`,
    `📍 From ${data.from_city || '—'}`,
    `💰 ₹${data.budget?.toLocaleString('en-IN') || '—'}`,
    data.trip_type ? `👤 ${data.trip_type}` : null,
  ].filter(Boolean)

  let px = ML
  metaItems.forEach(m => {
    const w = doc.getTextWidth(m) + 10
    rect(doc, px, 43, w, 7, [255, 255, 255, 0.1], 3) // semi-transparent not supported, use slate
    rect(doc, px, 43, w, 7, [30, 41, 59], 3)
    text(doc, m, px + 5, 48, { size: 8, color: [148, 163, 184] })
    px += w + 4
  })

  // Summary
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  setTextC(doc, C.slate)
  const sumLines = doc.splitTextToSize(data.summary || '', CW)
  doc.text(sumLines.slice(0, 2), ML, 60)

  // Agent / User branding strip
  if (isAgent) {
    rect(doc, 0, 68, PW, 10, C.teal)
    text(doc, `Prepared for: ${clientName || 'Your Client'}`, ML, 74.5, { size: 8.5, bold: true, color: C.white })
    text(doc, `By: ${agentName}`, MR, 74.5, { size: 8.5, color: C.white, align: 'right' })
  } else {
    rect(doc, 0, 68, PW, 10, C.teal)
    text(doc, `Prepared for: ${userName}`, ML, 74.5, { size: 8.5, bold: true, color: C.white })
    text(doc, `Generated on: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, MR, 74.5, { size: 8.5, color: C.white, align: 'right' })
  }

  let y = 90

  // ── HIGHLIGHTS ─────────────────────────────────────────────
  if (data.highlights?.length > 0) {
    y = sectionHeader(doc, y, 'TRIP HIGHLIGHTS', '✨')
    const cols = 2
    const colW = CW / cols - 4
    data.highlights.slice(0, 6).forEach((h, i) => {
      const col = i % cols
      const row = Math.floor(i / cols)
      const hx = ML + col * (colW + 8)
      const hy = y + row * 12

      rect(doc, hx, hy - 4, colW, 10, C.tealLight, 3)
      // Teal dot
      setFill(doc, C.teal)
      doc.circle(hx + 4, hy + 0.5, 1.5, 'F')
      text(doc, h, hx + 8, hy + 1, { size: 8.5, maxWidth: colW - 10 })
    })
    y += Math.ceil(data.highlights.slice(0, 6).length / 2) * 12 + 8
  }

  // ── COST BREAKDOWN ─────────────────────────────────────────
  y = checkPage(doc, y, 50)
  if (data.cost_breakdown && Object.keys(data.cost_breakdown).length > 0) {
    y = sectionHeader(doc, y, 'COST BREAKDOWN', '💰')

    const cb = data.cost_breakdown
    const costRows = [
      { label: 'Transport',     val: cb.transport,     icon: '🚂' },
      { label: 'Accommodation', val: cb.accommodation, icon: '🏨' },
      { label: 'Food',          val: cb.food,          icon: '🍽' },
      { label: 'Activities',    val: cb.activities,    icon: '🎯' },
      { label: 'Miscellaneous', val: cb.miscellaneous, icon: '📦' },
    ].filter(r => r.val)

    const colW2 = CW / 2 - 4
    costRows.forEach((r, i) => {
      const col = i % 2
      const row = Math.floor(i / 2)
      const cx = ML + col * (colW2 + 8)
      const cy = y + row * 11

      rect(doc, cx, cy - 3.5, colW2, 9, C.slateLight, 3)
      text(doc, `${r.icon} ${r.label}`, cx + 4, cy + 1.5, { size: 8, color: C.slate })
      text(doc, r.val, cx + colW2 - 4, cy + 1.5, { size: 9, bold: true, color: C.navy, align: 'right' })
    })

    y += Math.ceil(costRows.length / 2) * 11 + 4

    // Total bar
    rect(doc, ML, y, CW, 12, C.navy, 4)
    text(doc, 'TOTAL ESTIMATED COST', ML + 6, y + 8, { size: 9, bold: true, color: C.teal })
    text(doc, cb.total || '—', MR - 4, y + 8, { size: 12, bold: true, color: C.white, align: 'right' })
    y += 18
  }

  // ── DAY PLANS ──────────────────────────────────────────────
  y = checkPage(doc, y, 20)
  if (data.day_plans?.length > 0) {
    y = sectionHeader(doc, y, 'DAY-WISE ITINERARY', '📅')

    data.day_plans.forEach((day, i) => {
      y = checkPage(doc, y, 40)

      if (i > 0) {
        miniHeader(doc, data.destination)
        y = Math.max(y, 20)
      }

      // Day header
      rect(doc, ML, y, CW, 10, C.teal, 3)
      text(doc, `Day ${day.day}`, ML + 5, y + 7, { size: 10, bold: true, color: C.white })
      text(doc, day.title || '', ML + 22, y + 7, { size: 9, color: [204, 251, 241] })
      if (day.estimated_cost) {
        text(doc, day.estimated_cost, MR - 3, y + 7, { size: 8.5, bold: true, color: C.white, align: 'right' })
      }
      y += 13

      // Time slots
      const slots = [
        { label: '🌅 Morning',   val: day.morning },
        { label: '☀️ Afternoon', val: day.afternoon },
        { label: '🌙 Evening',   val: day.evening },
      ].filter(s => s.val)

      slots.forEach(slot => {
        y = checkPage(doc, y, 16)
        text(doc, slot.label, ML + 2, y, { size: 8, bold: true, color: C.tealDark })
        y += 4
        const h = wrap(doc, slot.val, ML + 2, y, CW - 4, { size: 8.5, color: C.navy, lineH: 5 })
        y += h + 2
      })

      // Meals / Stay
      const extras = [
        day.meals ? `🍽 Meals: ${day.meals}` : null,
        day.stay   ? `🏨 Stay: ${day.stay}`   : null,
      ].filter(Boolean)

      if (extras.length > 0) {
        y = checkPage(doc, y, 10)
        rect(doc, ML, y - 2, CW, extras.length * 7 + 2, C.slateLight, 2)
        extras.forEach(e => {
          text(doc, e, ML + 4, y + 3, { size: 8, color: C.slate })
          y += 7
        })
      }

      y += 8

      // Separator between days
      if (i < data.day_plans.length - 1) {
        line(doc, ML, y - 4, MR, y - 4, C.border)
      }
    })
  }

  // ── ACCOMMODATION ──────────────────────────────────────────
  y = checkPage(doc, y, 40)
  if (data.accommodation?.length > 0) {
    y = sectionHeader(doc, y, 'RECOMMENDED HOTELS', '🏨')

    data.accommodation.slice(0, 4).forEach((h, i) => {
      y = checkPage(doc, y, 28)
      rect(doc, ML, y, CW, 22, C.white, 3)
      setDraw(doc, C.border)
      doc.setLineWidth(0.3)
      doc.roundedRect(ML, y, CW, 22, 3, 3, 'S')

      // Hotel name
      text(doc, h.name, ML + 5, y + 7, { size: 9.5, bold: true, color: C.navy })
      // Rating stars
      const stars = '★'.repeat(Math.round(parseFloat(h.rating) || 4))
      text(doc, stars, MR - 4, y + 7, { size: 9, color: C.gold, align: 'right' })
      // Area
      text(doc, h.area || '', ML + 5, y + 13, { size: 8, color: C.slate })
      // Price
      text(doc, h.price_range || '', MR - 4, y + 13, { size: 8.5, bold: true, color: C.teal, align: 'right' })
      // Why
      if (h.why) {
        const wLines = doc.splitTextToSize(`💡 ${h.why}`, CW - 10)
        text(doc, wLines[0], ML + 5, y + 19, { size: 7.5, color: C.slate })
      }

      y += 26
    })
  }

  // ── TRANSPORT ──────────────────────────────────────────────
  y = checkPage(doc, y, 40)
  if (data.transport_options?.length > 0) {
    y = sectionHeader(doc, y, 'TRANSPORT OPTIONS', '🚂')

    data.transport_options.slice(0, 3).forEach((t, i) => {
      y = checkPage(doc, y, 20)
      const colors = [[22, 163, 74], [2, 132, 199], [124, 58, 237]]
      const c = colors[i % colors.length]

      rect(doc, ML, y, 3, 16, c, 1)
      rect(doc, ML + 4, y, CW - 4, 16, C.slateLight, 3)

      text(doc, t.mode || `Option ${i + 1}`, ML + 8, y + 6, { size: 9, bold: true, color: C.navy })
      text(doc, `${t.duration || ''} · ${t.cost || ''}`, ML + 8, y + 12, { size: 8, color: C.slate })
      if (t.recommendation) {
        text(doc, t.recommendation, MR - 4, y + 9, { size: 7.5, color: C.teal, align: 'right' })
      }

      y += 20
    })
  }

  // ── LOCAL TIPS ─────────────────────────────────────────────
  y = checkPage(doc, y, 30)
  if (data.local_tips?.length > 0) {
    y = sectionHeader(doc, y, 'LOCAL TIPS', '💡')

    data.local_tips.slice(0, 5).forEach((tip, i) => {
      y = checkPage(doc, y, 14)
      rect(doc, ML, y - 3, CW, 11, [255, 251, 235], 3)
      setFill(doc, C.gold)
      doc.circle(ML + 5, y + 2, 1.5, 'F')
      const h = wrap(doc, tip, ML + 10, y + 2, CW - 14, { size: 8.5, color: C.navy, lineH: 5 })
      y += Math.max(12, h + 6)
    })
  }

  // ── PACKING LIST ───────────────────────────────────────────
  y = checkPage(doc, y, 30)
  const packList = data.weather?.pack?.length > 0 ? data.weather.pack : data.packing_list
  if (packList?.length > 0) {
    y = sectionHeader(doc, y, 'PACKING LIST', '🎒')

    const cols = 3
    const colW3 = CW / cols - 2
    packList.slice(0, 15).forEach((item, i) => {
      const col = i % cols
      const row = Math.floor(i / cols)
      const px2 = ML + col * (colW3 + 3)
      const py  = y + row * 9

      rect(doc, px2, py - 3, colW3, 8, C.tealLight, 2)
      setFill(doc, C.teal)
      doc.circle(px2 + 3.5, py + 1, 1.2, 'F')
      text(doc, item, px2 + 7, py + 1.5, { size: 7.5, color: C.navy, maxWidth: colW3 - 9 })
    })

    y += Math.ceil(packList.slice(0, 15).length / cols) * 9 + 6
  }

  // ── FINAL PAGE: BOOKING CTA (Agent only) ──────────────────
  if (isAgent) {
    y = checkPage(doc, y, 40)
    rect(doc, ML, y, CW, 30, C.navy, 5)
    text(doc, 'Ready to book this trip?', ML + CW / 2, y + 10, { size: 13, bold: true, color: C.white, align: 'center' })
    text(doc, `Contact ${agentName} to confirm your booking`, ML + CW / 2, y + 18, { size: 9, color: C.teal, align: 'center' })
    text(doc, 'Powered by Tripzio AI · tripzio.io', ML + CW / 2, y + 25, { size: 8, color: C.slate, align: 'center' })
    y += 36
  } else {
    y = checkPage(doc, y, 30)
    rect(doc, ML, y, CW, 24, C.tealLight, 5)
    setDraw(doc, C.teal)
    doc.setLineWidth(0.5)
    doc.roundedRect(ML, y, CW, 24, 5, 5, 'S')
    text(doc, '✈️  Plan more trips at tripzio.io', ML + CW / 2, y + 10, { size: 11, bold: true, color: C.tealDark, align: 'center' })
    text(doc, 'India\'s AI-Powered Travel Intelligence Platform', ML + CW / 2, y + 18, { size: 8.5, color: C.slate, align: 'center' })
    y += 30
  }

  // ── Add mini headers + footers to all pages ────────────────
  const totalPages = doc.getNumberOfPages()
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p)
    if (p > 1) miniHeader(doc, data.destination)
    footer(doc, p, totalPages, isAgent, agentName)
  }

  // ── Save ───────────────────────────────────────────────────
  const filename = isAgent
    ? `Tripzio_${(data.destination || 'Trip').replace(/[^a-zA-Z0-9]/g, '_')}_${clientName || 'Client'}_Plan.pdf`
    : `Tripzio_${(data.destination || 'Trip').replace(/[^a-zA-Z0-9]/g, '_')}_${data.days || ''}Days.pdf`

  doc.save(filename)
}
