/**
 * frontend/src/utils/generatePDF.js
 * Tripzio — Premium PDF Generator (User + Agent)
 * No emojis — jsPDF Helvetica only supports Latin characters
 */

import { jsPDF } from 'jspdf'


// ── Sanitize: strip non-Latin chars that break Helvetica ─────
// Replaces rupee sign, arrows, and any char > 0xFF with safe equivalents
function san(str) {
  if (!str) return ''
  let s = String(str)
  // Replace common non-Latin chars that break jsPDF Helvetica
  const replacements = [
    [8377, 'Rs.'],  // rupee sign
    [8594, '->'],   // right arrow
    [8592, '<-'],   // left arrow
    [8211, '-'],    // en dash
    [8212, '--'],   // em dash
    [8216, "'"],    // left single quote
    [8217, "'"],    // right single quote
    [8220, '"'],    // left double quote
    [8221, '"'],    // right double quote
  ]
  let result = ''
  for (let i = 0; i < s.length; i++) {
    const code = s.charCodeAt(i)
    const rep = replacements.find(r => r[0] === code)
    if (rep) { result += rep[1]; continue }
    result += code <= 255 ? s[i] : ''  // drop anything outside Latin-1
  }
  return result
}

// ── Palette ───────────────────────────────────────────────────
const C = {
  teal:       [13,  148, 136],
  tealDark:   [15,  118, 110],
  tealLight:  [232, 249, 246],
  tealMid:    [153, 246, 228],
  navy:       [15,  23,  42],
  navyMid:    [30,  41,  59],
  slate:      [71,  85,  105],
  slateLight: [226, 232, 240],
  muted:      [148, 163, 184],
  white:      [255, 255, 255],
  offWhite:   [248, 250, 252],
  gold:       [217, 119, 6],
  goldLight:  [254, 243, 199],
  green:      [21,  128, 61],
  greenLight: [220, 252, 231],
  red:        [185, 28,  28],
}

const TIER_BG = {
  bronze:   [254, 243, 199],
  silver:   [241, 245, 249],
  gold:     [254, 249, 195],
  diamond:  [239, 246, 255],
  platinum: [250, 245, 255],
}
const TIER_FG = {
  bronze:   [146, 64,  14],
  silver:   [51,  65,  85],
  gold:     [133, 77,  14],
  diamond:  [29,  78,  216],
  platinum: [107, 33,  168],
}
const TIER_LABEL = {
  bronze:   'BRONZE PLAN',
  silver:   'SILVER PLAN',
  gold:     'GOLD PLAN',
  diamond:  'DIAMOND PLAN',
  platinum: 'PLATINUM PLAN',
}

// ── Core helpers ──────────────────────────────────────────────
const PW = 210, ML = 14, MR = 196, CW = MR - ML

function sf(doc, arr)  { doc.setFillColor(arr[0], arr[1], arr[2]) }
function sd(doc, arr)  { doc.setDrawColor(arr[0], arr[1], arr[2]) }
function st(doc, arr)  { doc.setTextColor(arr[0], arr[1], arr[2]) }

function box(doc, x, y, w, h, fill, r = 0, stroke = null, sw = 0.3) {
  sf(doc, fill)
  if (stroke) { sd(doc, stroke); doc.setLineWidth(sw) }
  const style = stroke ? 'FD' : 'F'
  if (r > 0) doc.roundedRect(x, y, w, h, r, r, style)
  else doc.rect(x, y, w, h, style)
}

function ln(doc, x1, y1, x2, y2, color = C.slateLight, lw = 0.25) {
  doc.setLineWidth(lw)
  sd(doc, color)
  doc.line(x1, y1, x2, y2)
}

function txt(doc, str, x, y, {
  size = 10, weight = 'normal', color = C.navy,
  align = 'left', maxW = null
} = {}) {
  doc.setFontSize(size)
  doc.setFont('helvetica', weight)
  st(doc, color)
  const s = String(str ?? '')
  if (maxW) {
    const lines = doc.splitTextToSize(s, maxW)
    doc.text(lines, x, y, { align })
    return lines.length
  }
  doc.text(s, x, y, { align })
  return 1
}

function wrp(doc, str, x, y, maxW, { size = 9, color = C.slate, lh = 5 } = {}) {
  doc.setFontSize(size)
  doc.setFont('helvetica', 'normal')
  st(doc, color)
  const lines = doc.splitTextToSize(san(String(str ?? '')), maxW)
  doc.text(lines, x, y)
  return lines.length * lh
}

function newPage(doc, y, needed = 35) {
  if (y + needed > 272) { doc.addPage(); return 18 }
  return y
}

// ── Structural components ─────────────────────────────────────

function pageTopBar(doc, destination) {
  box(doc, 0, 0, PW, 9, C.navy)
  ln(doc, 0, 9, PW, 9, C.teal, 0.5)
  txt(doc, 'TRIPZIO', ML, 6.2, { size: 7, weight: 'bold', color: C.teal })
  txt(doc, '|  ' + san(destination), ML + 22, 6.2, { size: 7, color: C.muted })
  txt(doc, 'tripzio.io', MR, 6.2, { size: 7, color: C.muted, align: 'right' })
}

function pageFooter(doc, pageNum, total, isAgent, agentName) {
  const fy = 283
  ln(doc, ML, fy, MR, fy, C.slateLight, 0.3)
  const left = isAgent
    ? `Prepared by ${san(agentName)}  |  Powered by Tripzio AI`
    : 'Generated by Tripzio AI  |  tripzio.io'
  txt(doc, left, ML, fy + 5, { size: 7, color: C.muted })
  txt(doc, `Page ${pageNum} / ${total}`, MR, fy + 5, { size: 7, color: C.muted, align: 'right' })
}

function secHead(doc, y, label) {
  // Left accent bar + label
  box(doc, ML, y, 2.5, 7, C.teal)
  txt(doc, label, ML + 6, y + 5.2, { size: 9.5, weight: 'bold', color: C.navy })
  ln(doc, ML + 6, y + 7.5, MR, y + 7.5, C.slateLight, 0.25)
  return y + 13
}

// ─────────────────────────────────────────────────────────────
// MAIN
// ─────────────────────────────────────────────────────────────

export function generateTripPDF({ data, user, isAgent = false, clientName = null }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  const agentName = user?.business_name || user?.full_name || 'Travel Agent'
  const userName  = user?.full_name || 'Traveler'
  const tier      = data.plan_tier || 'silver'
  const tierBg    = TIER_BG[tier]  || TIER_BG.silver
  const tierFg    = TIER_FG[tier]  || TIER_FG.silver
  const tierLabel = TIER_LABEL[tier] || 'SILVER PLAN'
  const dest      = san(data.destination || 'Your Trip')

  // ══════════════════════════════════════════════════════════
  // PAGE 1 — COVER
  // ══════════════════════════════════════════════════════════

  // Full dark hero
  box(doc, 0, 0, PW, 80, C.navy)
  // Top teal stripe
  box(doc, 0, 0, PW, 2, C.teal)

  // Brand bar
  txt(doc, 'TRIPZIO', ML, 14, { size: 13, weight: 'bold', color: C.teal })
  txt(doc, 'AI TRAVEL PLANNER', ML + 37, 14, { size: 7, color: C.muted })
  txt(doc, 'tripzio.io', MR, 14, { size: 8, color: C.muted, align: 'right' })

  // Tier badge
  box(doc, ML, 19, 36, 7, tierBg, 3.5)
  txt(doc, tierLabel, ML + 18, 24.2, { size: 7.5, weight: 'bold', color: tierFg, align: 'center' })

  // Destination — big
  txt(doc, dest, ML, 42, { size: 28, weight: 'bold', color: C.white })

  // Thin teal underline
  box(doc, ML, 45, Math.min(doc.getTextWidth(dest) * 0.85, CW), 1, C.teal)

  // Meta row
  const metaY = 53
  const metaItems = [
    `${data.days || '?'} DAYS`,
    `FROM  ${data.from_city || '--'}`,
    `BUDGET  Rs.${data.budget?.toLocaleString('en-IN') || '--'}`,
    data.trip_type ? `${data.trip_type.toUpperCase()} TRIP` : null,
  ].filter(Boolean)

  let mx = ML
  metaItems.forEach((m, i) => {
    if (i > 0) {
      // separator dot
      box(doc, mx, metaY + 1.5, 1.2, 1.2, C.muted)
      mx += 5
    }
    txt(doc, m, mx, metaY + 3.5, { size: 7.5, weight: 'bold', color: C.muted })
    mx += doc.getTextWidth(m) + 3
  })

  // Summary text
  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'normal')
  st(doc, [148, 163, 184])
  const sumLines = doc.splitTextToSize(san(data.summary || ''), CW - 10)
  doc.text(sumLines.slice(0, 2), ML, 63)

  // Prepared-for strip
  box(doc, 0, 74, PW, 12, C.teal)
  const leftLabel = isAgent ? `Prepared for:  ${san(clientName || 'Client')}` : `Prepared for:  ${san(userName)}`
  const rightLabel = isAgent ? `By:  ${san(agentName)}` : `Date:  ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`
  txt(doc, leftLabel,  ML, 81.5, { size: 8.5, weight: 'bold', color: C.white })
  txt(doc, rightLabel, MR, 81.5, { size: 8.5, color: C.white, align: 'right' })

  let y = 95

  // ── HIGHLIGHTS ──────────────────────────────────────────────
  if (data.highlights?.length > 0) {
    y = secHead(doc, y, 'TRIP HIGHLIGHTS')
    const colW = (CW - 6) / 2
    data.highlights.slice(0, 6).forEach((h, i) => {
      const col = i % 2
      const row = Math.floor(i / 2)
      const hx = ML + col * (colW + 6)
      const hy = y + row * 13

      box(doc, hx, hy, colW, 11, C.tealLight, 3)
      // Left accent
      box(doc, hx, hy, 2.5, 11, C.teal, 1.5)
      txt(doc, san(h), hx + 6, hy + 7, { size: 8, maxW: colW - 9 })
    })
    y += Math.ceil(Math.min(data.highlights.length, 6) / 2) * 13 + 6
  }

  // ── COST BREAKDOWN ──────────────────────────────────────────
  y = newPage(doc, y, 55)
  if (data.cost_breakdown) {
    y = secHead(doc, y, 'COST BREAKDOWN')
    const cb = data.cost_breakdown
    const rows = [
      { label: 'Transport',      val: san(cb.transport) },
      { label: 'Accommodation',  val: san(cb.accommodation) },
      { label: 'Food & Dining',  val: san(cb.food) },
      { label: 'Activities',     val: san(cb.activities) },
      { label: 'Miscellaneous',  val: san(cb.miscellaneous) },
    ].filter(r => r.val)

    const cw2 = (CW - 5) / 2
    rows.forEach((r, i) => {
      const col = i % 2
      const row = Math.floor(i / 2)
      const cx = ML + col * (cw2 + 5)
      const cy = y + row * 12

      box(doc, cx, cy, cw2, 10, C.offWhite, 3, C.slateLight)
      txt(doc, r.label, cx + 5,        cy + 6.5, { size: 8,   color: C.slate })
      txt(doc, r.val,   cx + cw2 - 4,  cy + 6.5, { size: 8.5, weight: 'bold', color: C.navy, align: 'right' })
    })
    y += Math.ceil(rows.length / 2) * 12 + 5

    // Total bar
    box(doc, ML, y, CW, 13, C.navy, 4)
    box(doc, ML, y, 4, 13, C.teal, 2)
    txt(doc, 'TOTAL ESTIMATED COST', ML + 8, y + 8.5, { size: 9, weight: 'bold', color: C.teal })
    txt(doc, san(String(cb.total || '--')), MR - 5, y + 8.5, { size: 11, weight: 'bold', color: C.white, align: 'right' })
    y += 20
  }

  // ── DAY-WISE ITINERARY ───────────────────────────────────────
  y = newPage(doc, y, 20)
  if (data.day_plans?.length > 0) {
    y = secHead(doc, y, 'DAY-WISE ITINERARY')

    data.day_plans.forEach((day, idx) => {
      // Estimate this day's total height to decide if we need a new page
      const slotCount = [day.morning, day.afternoon, day.evening].filter(Boolean).length
      const extrasCount = [day.meals, day.stay].filter(Boolean).length
      const estimatedHeight = 14 + (slotCount * 22) + (extrasCount * 8) + 12
      y = newPage(doc, y, estimatedHeight)

      if (y < 20) y = 20

      // Day header bar
      box(doc, ML, y, CW, 11, C.teal, 3)
      txt(doc, `DAY ${day.day}`, ML + 5, y + 7.5, { size: 9, weight: 'bold', color: C.white })
      txt(doc, san(day.title || ''), ML + 24, y + 7.5, { size: 8.5, color: [204, 251, 241] })
      if (day.estimated_cost) {
        txt(doc, san(day.estimated_cost), MR - 4, y + 7.5, { size: 8.5, weight: 'bold', color: C.white, align: 'right' })
      }
      y += 14

      // ── Time slots — 3-column icon-tab layout ──────────────────
      const SLOT_ICON_W = 24  // left icon column width
      const SLOT_TEXT_W = CW - SLOT_ICON_W - 4

      const slotDefs = [
        { label: 'MORNING',   icon: 'AM', val: san(day.morning),   bg: [232,249,246], fg: C.tealDark, bar: C.teal },
        { label: 'AFTERNOON', icon: 'PM', val: san(day.afternoon), bg: [239,246,255], fg: [29,78,216], bar: [59,130,246] },
        { label: 'EVENING',   icon: 'EV', val: san(day.evening),   bg: [250,245,255], fg: [107,33,168], bar: [139,92,246] },
      ].filter(s => s.val)

      slotDefs.forEach(slot => {
        y = newPage(doc, y, 20)
        if (y < 20) y = 20

        // Estimate text height for this slot
        doc.setFontSize(9)
        const textLines = doc.splitTextToSize(slot.val, SLOT_TEXT_W - 4)
        const textH = Math.max(textLines.length * 5, 10)
        const rowH = textH + 10  // padding top + bottom

        // Row background
        box(doc, ML, y, CW, rowH, slot.bg, 3)

        // Left colour tab (icon column)
        box(doc, ML, y, SLOT_ICON_W, rowH, slot.bar, 3)

        // Icon label (centered in tab)
        txt(doc, slot.icon, ML + SLOT_ICON_W / 2, y + rowH / 2 - 1.5, {
          size: 7.5, weight: 'bold', color: C.white, align: 'center'
        })
        // Slot name below icon
        txt(doc, slot.label, ML + SLOT_ICON_W / 2, y + rowH / 2 + 3.5, {
          size: 5.5, color: [255,255,255], align: 'center'
        })

        // Text content in right column
        doc.setFontSize(9)
        doc.setFont('helvetica', 'normal')
        st(doc, C.navy)
        doc.text(textLines, ML + SLOT_ICON_W + 4, y + 8)

        y += rowH + 3
      })

      // Meals + Stay — inline pill row
      const mealVal = day.meals ? san(day.meals) : null
      const stayVal = day.stay  ? san(day.stay)  : null

      if (mealVal || stayVal) {
        y = newPage(doc, y, 12)
        if (y < 20) y = 20

        // Single row with two pills side by side
        const halfW = (CW - 4) / 2
        if (mealVal) {
          box(doc, ML, y, halfW, 10, C.offWhite, 3, C.slateLight, 0.3)
          txt(doc, 'MEALS', ML + 4, y + 4.5, { size: 6.5, weight: 'bold', color: C.tealDark })
          wrp(doc, mealVal, ML + 4, y + 8.5, halfW - 6, { size: 7.5, color: C.navy, lh: 4.5 })
        }
        if (stayVal) {
          const sx = ML + halfW + 4
          box(doc, sx, y, halfW, 10, C.offWhite, 3, C.slateLight, 0.3)
          txt(doc, 'STAY', sx + 4, y + 4.5, { size: 6.5, weight: 'bold', color: C.tealDark })
          wrp(doc, stayVal, sx + 4, y + 8.5, halfW - 6, { size: 7.5, color: C.navy, lh: 4.5 })
        }
        y += 14
      }

      // Day separator
      if (idx < data.day_plans.length - 1) {
        y += 4
        ln(doc, ML, y, MR, y, C.slateLight)
        y += 6
      } else {
        y += 8
      }
    })
  }

  // ── HOTELS ──────────────────────────────────────────────────
  y = newPage(doc, y, 45)
  if (data.accommodation?.length > 0) {
    y = secHead(doc, y, 'RECOMMENDED HOTELS')

    data.accommodation.slice(0, 4).forEach((h, i) => {
      y = newPage(doc, y, 28)

      box(doc, ML, y, CW, 24, C.white, 3, C.slateLight, 0.3)
      // Left colour bar
      const barColors = [C.teal, C.navyMid, C.gold, [124, 58, 237]]
      box(doc, ML, y, 3, 24, barColors[i % 4], 2)

      txt(doc, san(h.name || `Hotel ${i+1}`),  ML + 7,      y + 8,  { size: 10, weight: 'bold', color: C.navy })
      txt(doc, san(h.area || ''),              ML + 7,      y + 14, { size: 8,  color: C.slate })

      // Stars as text
      const starCount = Math.round(parseFloat(h.rating) || 4)
      const stars = Array(starCount).fill('*').join(' ')
      txt(doc, stars, MR - 5, y + 8, { size: 9, weight: 'bold', color: C.gold, align: 'right' })

      txt(doc, san(h.price_range || ''),  MR - 5,  y + 14, { size: 8.5, weight: 'bold', color: C.teal, align: 'right' })

      if (h.why) {
        const wl = doc.splitTextToSize(san(h.why), CW - 14)
        txt(doc, wl[0] || '', ML + 7, y + 20, { size: 7.5, color: C.muted })
      }

      y += 28
    })
  }

  // ── TRANSPORT ───────────────────────────────────────────────
  y = newPage(doc, y, 45)
  if (data.transport_options?.length > 0) {
    y = secHead(doc, y, 'TRANSPORT OPTIONS')

    const tColors = [C.teal, C.gold, [124, 58, 237]]
    data.transport_options.slice(0, 3).forEach((t, i) => {
      y = newPage(doc, y, 20)
      const c = tColors[i % 3]

      box(doc, ML,     y, CW,   18, C.offWhite, 3)
      box(doc, ML,     y, 3,    18, c, 1.5)

      txt(doc, san(t.mode || `Option ${i+1}`).toUpperCase(), ML + 7, y + 7, { size: 8.5, weight: 'bold', color: C.navy })
      const sub = [san(t.duration), san(t.cost)].filter(Boolean).join('  |  ')
      txt(doc, sub, ML + 7, y + 13, { size: 8, color: C.slate })
      if (t.recommendation) {
        txt(doc, san(t.recommendation), MR - 4, y + 10, { size: 7.5, color: c, align: 'right', maxW: 70 })
      }
      y += 22
    })
  }

  // ── LOCAL TIPS ──────────────────────────────────────────────
  y = newPage(doc, y, 35)
  if (data.local_tips?.length > 0) {
    y = secHead(doc, y, 'LOCAL TIPS & ADVICE')

    data.local_tips.slice(0, 6).forEach((tip, i) => {
      y = newPage(doc, y, 16)
      box(doc, ML, y, CW, 14, C.goldLight, 3)
      box(doc, ML, y, 3, 14, C.gold, 1.5)
      // Number
      txt(doc, String(i + 1).padStart(2, '0'), ML + 6, y + 9, { size: 8, weight: 'bold', color: C.gold })
      const h = wrp(doc, san(tip), ML + 16, y + 5, CW - 20, { size: 8.5, color: C.navy, lh: 5 })
      y += Math.max(16, h + 8)
    })
  }

  // ── CTA BLOCK ───────────────────────────────────────────────
  y = newPage(doc, y, 35)
  y += 5
  box(doc, ML, y, CW, 28, C.navy, 5)
  box(doc, ML, y, CW, 3, C.teal, 2.5)

  if (isAgent) {
    txt(doc, 'Ready to confirm this itinerary?', ML + CW/2, y + 13, { size: 12, weight: 'bold', color: C.white, align: 'center' })
    txt(doc, `Contact ${agentName} to book`, ML + CW/2, y + 20, { size: 9, color: C.tealMid, align: 'center' })
    txt(doc, 'Powered by Tripzio AI  |  tripzio.io', ML + CW/2, y + 26, { size: 7.5, color: C.muted, align: 'center' })
  } else {
    txt(doc, 'Plan more trips at tripzio.io', ML + CW/2, y + 13, { size: 12, weight: 'bold', color: C.white, align: 'center' })
    txt(doc, "India's AI-Powered Travel Intelligence Platform", ML + CW/2, y + 20, { size: 9, color: C.tealMid, align: 'center' })
    txt(doc, 'Free to use  |  Instant itineraries  |  500+ destinations', ML + CW/2, y + 26, { size: 7.5, color: C.muted, align: 'center' })
  }

  // ── Apply headers + footers to all pages ───────────────────
  const totalPages = doc.getNumberOfPages()
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p)
    if (p > 1) pageTopBar(doc, dest)
    pageFooter(doc, p, totalPages, isAgent, agentName)
  }

  // ── Save ───────────────────────────────────────────────────
  const safeDest = dest.replace(/[^a-zA-Z0-9\s]/g, '').replace(/\s+/g, '_')
  const filename = isAgent
    ? `Tripzio_${safeDest}_${(clientName || 'Client').replace(/\s/g, '_')}_Plan.pdf`
    : `Tripzio_${safeDest}_${data.days || ''}Days.pdf`

  doc.save(filename)
}
